### PR TITLE
Add auto-start and start/stop following the built-in virtual camera

### PR DESCRIPTION
**Pull request by rse**
For the virtual camera filters, add auto-start and start/stop following the built-in virtual camera

### CODE REVIEW

**Comment by billy-sung** [comment]
I saw previous pr closed. is this pr ready for review?

**Comment by miaulightouch** [comment]
I saw previous pr closed, is this pr ready for review?

**Comment by rse** [comment]
Yes, sorry for the confusion: I just moved the code to a branch on my side, so I had to open a new PR for the new branch. The autostart feature is ready for review by you. I'm using it actually in production of our company filmstudio since three weeks without problems, so it was even tested in practice.

**Comment by miaulightouch** [comment]
fix the formatting, then I think it would be ready to merge.

**Comment by rse** [comment]
I've fixed the formatting in my touched files. Why you actions also complain about two files I've not even touched, I don't understand. But I've now also fixed the formatting there, too.

**Comment by miaulightouch** [comment]
I also double checked the previous CI log, before I left the comment. I don’t know how’s it failing the check between these builds.

**Comment by rse** [comment]
I've now tried to fix the formatting.

**Pull request merged**
